In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\data\propiedades_agregadas_usuario.csv')
df

,user,hotel_recomendado,hotel_ejemplo_id,numero_propiedades,lista_propiedades
0,3,104,457,1,category:Tours
1,3,104,2513,1,category:Tours
2,3,104,1941,2,attribute:RestaurantsPriceRange2=2 | attribute...
3,3,104,1783,3,attribute:BusinessAcceptsCreditCards=True | at...
4,3,1054,457,2,city:Philadelphia | state:PA
...,...,...,...,...,...
195,3,901,1783,5,city:Philadelphia | state:PA | postal_code:191...
196,3,907,457,4,city:Philadelphia | state:PA | postal_code:191...
197,3,907,2513,5,city:Philadelphia | state:PA | postal_code:191...
198,3,907,1941,4,state:PA | category:Event Planning & Services ...
199,3,907,1783,9,city:Philadelphia | state:PA | postal_code:191...

In [ ]:
df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\data\propiedades_compartidas.csv')
df

,usuario,hotel_recomendado,hotel_recomendado_nombre,num_explicaciones,precision_promedio,precision_max,precision_std,cobertura_total,propiedades_unicas_mencionadas,diversidad_entropia,diversidad_normalizada,utilidad_promedio,utilidad_max,preference_coverage,blind_spot_coverage
0,3,25,Cathedral-Basilica of St. Louis King of France,4,0.000000,0.000000,0.000000,0.0,5,2.231270,0.960956,0.320000,0.426667,0.133333,0.866667
1,3,45,Philadelphia International Airport - PHL,4,0.516667,0.666667,0.110554,1.0,5,2.188722,0.942631,0.355556,0.426667,0.133333,0.866667
2,3,104,French Market,4,0.208333,0.500000,0.250000,0.5,5,2.235926,0.962961,0.248889,0.426667,0.133333,0.866667
3,3,163,Panorama,4,0.342262,0.500000,0.110561,1.0,9,2.974938,0.938488,0.444444,0.444444,0.222222,0.777778
4,3,393,Linvilla Orchards,4,0.541667,0.666667,0.083333,1.0,6,2.368523,0.916270,0.359259,0.431111,0.155556,0.844444
5,3,473,Ryman Auditorium,4,0.156250,0.500000,0.236621,0.5,11,3.378783,0.976687,0.340000,0.453333,0.266667,0.733333
6,3,522,Nashville International Airport - BNA,4,0.187500,0.500000,0.239357,0.5,4,1.918296,0.959148,0.175926,0.422222,0.111111,0.888889
7,3,774,The National WWII Museum,4,0.000000,0.000000,0.000000,0.0,8,2.842371,0.947457,0.330000,0.440000,0.200000,0.800000
8,3,888,Embassy Suites by Hilton New Orleans,4,0.114583,0.333333,0.157288,0.5,10,3.277613,0.986660,0.224444,0.448889,0.244444,0.755556
9,3,901,Renaissance Philadelphia Downtown Hotel,4,0.366667,0.400000,0.038490,1.0,7,2.655639,0.945958,0.435556,0.435556,0.177778,0.822222
10,3,907,National Constitution Center,4,0.293056,0.500000,0.139471,1.0,12,3.390805,0.945841,0.457778,0.457778,0.288889,0.711111
11,3,1054,Kimpton Hotel Palomar Philadelphia,4,0.458333,0.500000,0.083333,1.0,6,2.411602,0.932935,0.395185,0.431111,0.155556,0.844444
12,3,1093,Tucson International Airport - TUS,4,0.000000,0.000000,0.000000,0.0,4,1.921928,0.960964,0.175926,0.281481,0.111111,0.888889
13,3,1164,Mardi Gras World-Riverfront,4,0.175000,0.500000,0.236291,0.5,8,2.921928,0.973976,0.293333,0.440000,0.200000,0.800000
14,3,1442,Louis Armstrong New Orleans International Airp...,4,0.000000,0.000000,0.000000,0.0,6,2.521641,0.975504,0.215556,0.431111,0.155556,0.844444
15,3,1487,Ride The Ducks,4,0.437500,1.000000,0.375000,0.5,5,2.199688,0.947354,0.351852,0.422222,0.111111,0.888889
16,3,1608,Ultimate Swamp Adventures,4,0.000000,0.000000,0.000000,0.0,4,1.950212,0.975106,0.246296,0.422222,0.111111,0.888889
17,3,1693,William Penn Inn,4,0.604167,1.000000,0.314576,1.0,10,3.093069,0.931107,0.336667,0.448889,0.244444,0.755556
18,3,1729,Conner Prairie,4,0.291667,1.000000,0.478714,0.5,8,2.913977,0.971326,0.293333,0.440000,0.200000,0.800000
19,3,2085,Missouri Botanical Garden,4,0.152778,0.500000,0.237333,0.5,10,3.235926,0.974111,0.299259,0.448889,0.244444,0.755556
20,3,2101,Indianapolis Motor Speedway Museum,4,0.000000,0.000000,0.000000,0.0,9,3.084963,0.973197,0.296296,0.444444,0.222222,0.777778
21,3,2109,Hyatt Regency St. Louis at the Arch,4,0.208333,0.500000,0.250000,0.5,3,1.521928,0.960230,0.174074,0.417778,0.088889,0.911111
22,3,2290,Southwest Airlines,4,0.000000,0.000000,0.000000,0.0,1,0.000000,0.000000,0.034074,0.136296,0.044444,0.955556
23,3,2344,Gaylord Opryland Resort & Convention Center,4,0.125000,0.333333,0.159571,0.5,8,2.947703,0.982568,0.220000,0.440000,0.200000,0.800000
24,3,2557,Indianapolis International Airport - IND,4,0.000000,0.000000,0.000000,0.0,3,1.500000,0.946395,0.139259,0.278519,0.088889,0.911111
25,3,2617,"Union Station Hotel Nashville, Autograph Colle...",4,0.187500,0.500000,0.239357,0.5,5,2.235926,0.962961,0.213333,0.426667,0.133333,0.866667
26,3,2963,One Liberty Observation Deck,4,0.266667,0.500000,0.156347,1.0,13,3.513270,0.949420,0.457778,0.457778,0.288889,0.711111
27,3,2972,Stearns Wharf,4,0.000000,0.000000,0.000000,0.0,7,2.625815,0.935334,0.326667,0.435556,0.177778,0.822222
28,3,3069,Avis Rent-A-Car - Tampa Intl Airport,4,0.000000,0.000000,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0.022222,0.977778
29,3,3119,"The Roosevelt New Orleans, A Waldorf Astoria H...",4,0.208333,0.500000,0.250000,0.5,4,1.918296,0.959148,0.211111,0.422222,0.111111,0.888889
30,3,3136,St. Charles Streetcar Line,4,0.000000,0.000000,0.000000,0.0,5,2.321928,1.000000,0.142222,0.426667,0.133333,0.866667
31,3,3165,Harrah's New Orleans,4,0.125000,0.250000,0.144338,0.5,6,2.500000,0.967132,0.215556,0.431111,0.155556,0.844444
32,3,3178,Megabus,4,0.625000,1.000000,0.250000,0.5,2,0.985228,0.985228,0.241111,0.275556,0.066667,0.933333
33,3,3209,30th Street Station,4,0.320833,0.500000,0.131498,0.5,6,2.413800,0.933785,0.395185,0.431111,0.155556,0.844444
34,3,3237,The Big Bus Company,4,0.416667,0.666667,0.204124,1.0,6,2.472906,0.956650,0.431111,0.431111,0.155556,0.844444
35,3,3484,PHLASH,4,0.500000,1.000000,0.333333,0.5,3,1.570951,0.991159,0.348148,0.417778,0.088889,0.911111
36,3,3732,Tampa International Airport,4,0.145833,0.333333,0.171796,0.5,6,2.500000,0.967132,0.251481,0.431111,0.155556,0.844444
37,3,3737,Septa 5th Street Station,4,0.625000,1.000000,0.250000,0.5,2,0.985228,0.985228,0.241111,0.275556,0.066667,0.933333
38,3,4088,The Gateway Arch,4,0.000000,0.000000,0.000000,0.0,8,2.815072,0.938357,0.330000,0.440000,0.200000,0.800000
39,3,4122,The Alexander,4,0.208333,0.500000,0.250000,0.5,4,1.918296,0.959148,0.211111,0.422222,0.111111,0.888889
40,3,4183,Le Pavillon Hotel,4,0.114583,0.333333,0.157288,0.5,9,3.095795,0.976615,0.222222,0.444444,0.222222,0.777778
41,3,4359,Johnny Cash Museum,4,0.160714,0.500000,0.236003,0.5,9,3.121928,0.984859,0.222222,0.444444,0.222222,0.777778
42,3,4464,Indianapolis Motor Speedway,4,0.114583,0.333333,0.157288,0.5,9,3.084963,0.973197,0.259259,0.444444,0.222222,0.777778
43,3,4825,Club Quarters Philadelphia,4,0.458333,0.500000,0.083333,1.0,7,2.610577,0.929906,0.362963,0.435556,0.177778,0.822222
44,3,4830,Philadelphia International Airport - Terminal F,4,0.437500,0.500000,0.125000,0.5,4,1.846439,0.923220,0.316667,0.422222,0.111111,0.888889
45,3,4942,Philadelphia Sightseeing Tours & Transportation,4,0.375000,0.500000,0.144338,1.0,7,2.655639,0.945958,0.435556,0.435556,0.177778,0.822222
46,3,4990,Peddler's Village,4,0.613095,1.000000,0.301404,1.0,9,2.931209,0.924693,0.333333,0.444444,0.222222,0.777778
47,3,5061,Woldenberg Park,4,0.000000,0.000000,0.000000,0.0,4,1.921928,0.960964,0.175926,0.281481,0.111111,0.888889
48,3,5605,Audubon Aquarium of the Americas,4,0.187500,0.500000,0.239357,0.5,6,2.500000,0.967132,0.251481,0.431111,0.155556,0.844444
49,3,5855,Free Tours By Foot,4,0.000000,0.000000,0.000000,0.0,1,0.000000,0.000000,0.068148,0.136296,0.044444,0.955556

In [ ]:
df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\data\scores_explicaciones_detalle.csv')
df

,user,hotel_recomendado,hotel_recomendado_nombre,hotel_ejemplo,hotel_ejemplo_id,numero_propiedades,lista_propiedades,usuario,preference_coverage,blind_spot_coverage,precision_individual,cobertura_individual,utilidad_individual
0,3,104,French Market,Elfreth's Alley,457,1,category:Tours,3,0.133333,0.866667,0.000000,0.0,0.142222
1,3,104,French Market,The Betsy Ross House,2513,1,category:Tours,3,0.133333,0.866667,0.000000,0.0,0.142222
2,3,104,French Market,Best Western Plus Philadelphia Airport South,1941,2,attribute:RestaurantsPriceRange2=2 | attribute...,3,0.133333,0.866667,0.500000,0.5,0.284444
3,3,104,French Market,Independence Visitor Center,1783,3,attribute:BusinessAcceptsCreditCards=True | at...,3,0.133333,0.866667,0.333333,0.5,0.426667
4,3,1054,Kimpton Hotel Palomar Philadelphia,Elfreth's Alley,457,2,city:Philadelphia | state:PA,3,0.155556,0.844444,0.500000,0.5,0.287407
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,901,Renaissance Philadelphia Downtown Hotel,Independence Visitor Center,1783,5,city:Philadelphia | state:PA | postal_code:191...,3,0.177778,0.822222,0.400000,1.0,0.435556
196,3,907,National Constitution Center,Elfreth's Alley,457,4,city:Philadelphia | state:PA | postal_code:191...,3,0.288889,0.711111,0.250000,0.5,0.457778
197,3,907,National Constitution Center,The Betsy Ross House,2513,5,city:Philadelphia | state:PA | postal_code:191...,3,0.288889,0.711111,0.200000,0.5,0.457778
198,3,907,National Constitution Center,Best Western Plus Philadelphia Airport South,1941,4,state:PA | category:Event Planning & Services ...,3,0.288889,0.711111,0.500000,1.0,0.457778
199,3,907,National Constitution Center,Independence Visitor Center,1783,9,city:Philadelphia | state:PA | postal_code:191...,3,0.288889,0.711111,0.222222,1.0,0.457778

In [ ]:
df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\data_2\hoteles_historicos_propiedades.csv')
df

In [ ]:
df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\data_2\propiedades_compartidas.csv')
df