In [6]:
import pandas as pd

df = pd.read_csv(r'C:\Users\cris\Desktop\MUSII\TFM\Sistema_recomendacion_xai_TFM_MUSII_CMN\extraccion_scores\data\resultados_metricas_cobertura.csv')
df

,user,hotel_recomendado,hotel_historico,numero_propiedades,lista_propiedades,num_ejemplos_hotel,promedio_props_hotel,max_props_hotel,min_props_hotel,std_props_hotel,num_recomendaciones_usuario,num_ejemplos_totales_usuario,promedio_props_usuario,max_props_usuario,min_props_usuario,std_props_usuario,cobertura_ejemplos_usuario,diversidad_usuario,tasa_sin_propiedades_usuario
0,3,104.0,457.0,1.0,category:Tours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,104.0,2513.0,1.0,category:Tours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,104.0,1941.0,2.0,attribute:RestaurantsPriceRange2=2 | attribute...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,104.0,1783.0,3.0,attribute:BusinessAcceptsCreditCards=True | at...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,1054.0,457.0,2.0,city:Philadelphia | state:PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,3,774.0,NaN,NaN,NaN,4.0,3.50,7.0,0.0,2.886751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,3,888.0,NaN,NaN,NaN,4.0,2.75,8.0,0.0,3.774917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,3,901.0,NaN,NaN,NaN,4.0,4.00,5.0,3.0,1.154701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,3,907.0,NaN,NaN,NaN,4.0,5.50,9.0,4.0,2.380476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,200.0,2.555,10.0,0.0,2.130651,4.0,0.051002,0.19

In [9]:
df_104 = df[df["hotel_recomendado"] == 104]
df_104

,user,hotel_recomendado,hotel_historico,numero_propiedades,lista_propiedades,num_ejemplos_hotel,promedio_props_hotel,max_props_hotel,min_props_hotel,std_props_hotel,num_recomendaciones_usuario,num_ejemplos_totales_usuario,promedio_props_usuario,max_props_usuario,min_props_usuario,std_props_usuario,cobertura_ejemplos_usuario,diversidad_usuario,tasa_sin_propiedades_usuario
0,3,104.0,457.0,1.0,category:Tours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,104.0,2513.0,1.0,category:Tours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,104.0,1941.0,2.0,attribute:RestaurantsPriceRange2=2 | attribute...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,104.0,1783.0,3.0,attribute:BusinessAcceptsCreditCards=True | at...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,3,104.0,NaN,NaN,NaN,4.0,1.75,3.0,1.0,0.957427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_907 = df[df["hotel_recomendado"] == 907]
df_907

,user,hotel_recomendado,hotel_historico,numero_propiedades,lista_propiedades,num_ejemplos_hotel,promedio_props_hotel,max_props_hotel,promedio_props_usuario,max_props_usuario,cobertura_ejemplos_usuario,diversidad_usuario
245,3,907,457.0,4.0,city:Philadelphia | state:PA | postal_code:191...,4,5.5,9,2.555,10,4.0,0.051002
246,3,907,2513.0,5.0,city:Philadelphia | state:PA | postal_code:191...,4,5.5,9,2.555,10,4.0,0.051002
247,3,907,1941.0,4.0,state:PA | category:Event Planning & Services ...,4,5.5,9,2.555,10,4.0,0.051002
248,3,907,1783.0,9.0,city:Philadelphia | state:PA | postal_code:191...,4,5.5,9,2.555,10,4.0,0.051002
249,3,907,NaN,NaN,NaN,4,5.5,9,2.555,10,4.0,0.051002